### ISSUE TITLE
myEigenFaces code line 31 mypca(A)

### ISSUE THREAD

**Issue by Mantsje** [RUG-IDS/Course-2018#15]
Hi,

In the code given for myEigenFaces it calls mypca(A). 
In pca on pictures, the individual pixels are the variables correct? The photo's are 23*28=644 pixels, or 644 variables. We have 200 pictures test_data.
Now the slides say: "PCA takes a data matrix of n objects by p variables, which may be correlated, and summarizes it by uncorrelated axes (principal components or principal axes) that are linear combinations of the original p variables"

This would be (N x P), so (200 x 644). However the data that was loaded in by the given code makes sure that A is (644 x 200). 

So now my question: should mypca(A) really be mypca(transpose(A))? Or am I missing something here?

Cheers, 
Edser

**Comment by geazzo** [comment]
If the data is already centered, that is having a mean of zeros, then it would not harm anything if you subtract the mean full of zeros from the centered data.
