### ISSUE TITLE
Question regarding report

### ISSUE THREAD

**Issue by Daanhiemstra** [RUG-IDS/Course-2018#16]
Dear TA's,

I have question regarding the style of report for the assignment. In the Latex Template for the Assignments document is stated that we need to follow a structure which is like Introduction, Methodology, Results, Discussion and Conclusion. However, in the same document there is stated that we need to answer each question seperately in the form of 2.1.a , 2.1.b etc. 

So my question is; what is expected from us? Do we need to adress each question in for example the discussion or results section? 
Or do we need to make a seperate section where we answer each question seperately?

Kind regards,

Team 06

**Comment by sreejita-rug** [comment]
Dear Team 06,
Please check the responses to the same issue https://github.com/RUG-IDS/Course-2018/issues/13 
This issue was raised there yesterday and have been answered there.
