### ISSUE TITLE
Having problems with API/JSON knowledge

### ISSUE THREAD

**Issue by willekemulder** [RUG-IDS/Course-2018#2]
Hi there! 

I'm having problems with Query a JSON API with the key from the exercise. I have never used JSON or API before. I'm using Python. With the commands 

r = requests.get("http://www.omdbapi.com/?apikey=[863c5282]&")
data = json.loads(r.text)

I am getting an error : {u'Response': u'False', u'Error': u'Invalid API key!'}

Is this because I first need to specify a specific OMDb ID in the url? 

Kind regards, Willeke

**Comment by kaustv-datta** [comment]
I am facing the same issue while testing the OMDB API using Chrome's Postman extension

![image](https://user-images.githubusercontent.com/6747425/44995115-f0d6bb00-afa1-11e8-928c-272a5fd902fa.png)

Regards,
Kaustav

**Comment by myuja** [comment]
The given API key seems broken. You can go here: [](http://www.omdbapi.com/apikey.aspx) and request one for yourself.

**Comment by rm-bwana** [comment]
Hello, 
Yes we can see there appears to be a problem with the API key provided. So you can indeed create a new API key using the link provided by @myuja .

We are also in the process of testing an alternative API which will still be able to provide the same information as the OMDB one. 

An announcement will be made and the Assignment document will be updated with the relevant information as soon as we have resolved the problem.

Rob.
