### ISSUE TITLE
Assignment schedule

### ISSUE THREAD

**Issue by Daanhiemstra** [RUG-IDS/Course-2018#21]
Dear TA's,

Do you have a schedule with al the assignment deadlines?

Kind regards,

**Comment by rm-bwana** [comment]
Hello,
Please consider the following list a tentative outline of the deadlines:

- 28.09: Material you will present with for flipped classroom presentation.
- 01.10: Assignment on Text Analysis.
- 01.10: Flipped Classroom presentation.
- 08.10: Report based on flipped classroom materials. 
- 15.10: Assignment on Unsupervised Methods
- 22.10: Assignment on Supervised Methods
- The exact nature and work required for Time Series is still to be decided. We will let you know as soon as possible.

Hope this helps,
Rob.
