### ISSUE TITLE
Finding feedback for first assignment on Nestor

### ISSUE THREAD

**Issue by sreejita-rug** [RUG-IDS/Course-2018#22]
Dear Students,

From the emails we received from some of you we understood that finding the feedback on Nestor might not have been very straightforward. We have no control over how Nestor works; we can only do what is in our power to help you. Hence this announcement. 

For those of you who have not been able to see the feedback on your 1st assignment, please click on the grade itself from the Grade center in Nestor. You will notice that the grade is actually a hyperlink and it will redirect you to the test itself. There you should be able to see the feedback for each of the questions where you got less grade.

Also in future, if you have such problems/doubts please create an issue on Github instead of mailing us individually. We will answer you on Github. If you're lucky, your classmates who might have already faced and tackled that same issue (in this case, unlocked the mysterious way of accessing the feedback on Nestor), will reply to your issue faster than us and can help you out.

Best wishes,
Your TAs

**Comment by Loes-Deuling** [comment]
The grade is not a hyperlink for me... How do I access the feeedback then?

**Comment by sreejita-rug** [comment]
Nestor -> Tools -> My Grades -> "First week: Individual assignment" -> under Calculated grade: the grade received is a hyperlink which redirects one to another page from where one can view his/her attempt and the feedback on the questions they received less grade

**Comment by charx7** [comment]
HI, I have checked the nestor tab for My Grades, although it is displaying the assignments: ex1, ex2 etc  I have not received a grade nor find the hyperlink or the grade, could you help me?

**Comment by drogaar** [comment]
Dear all,

After viewing the process on accessing the feedback with my team it looks like this functionality may indeed be flawed. The feedback is indeed available as a link on the grade in assessment details. In turn, assessment details is linked to from "First week: Individual assignment" in the grade center. However, the link in the grade center (First week: Individual assignment) is not available on my computers and browsers. The link is disabled and the cursor does not change, effectively hiding the link as well. On clicking, an uncaught TypeError is thrown, showing that some unintended behaviour is happening.

It is possible to manually see the feedback by inspecting the link element and copying the target of loadContentFrame and appending it to nestor.rug.nl in a new URL. This takes you to the assessment details page, where the grade should successfully link to feedback. Relying on this for future feedback should probably be avoided.

Kind regards,
Danny / team-14
