### ISSUE TITLE
Is it a shared presentation for team 06 and team 12?

### ISSUE THREAD

**Issue by Daanhiemstra** [RUG-IDS/Course-2018#24]
Dear TA's,

We have a question regarding the presentation assignment; we are scheduled together with team 12 with the same subject. Are we supposed to do the presentation together or do we need to do the same presentation seperately after eachother?

Kind regards,

Team 06

**Comment by rm-bwana** [comment]
Hello,

When you see two teams presenting at the same time in the same room it means that they will be presenting at opposite ends of the room to different audiences. 

Therefore each team will get the full 20 minutes in their own corner of the room and can present their own work.

Best,
Rob.

**Comment by Mantsje** [comment]
Hi,

How exactly do you think this is going to work out? I know the scheduling is tight and all, but I think that actually thinking that 2 groups can present at the same time is pretty naive.  How is this going to work out in a room for 30 people. 
1. There are usually not 2 projectors/screens to show slides on at the same time. 
2. Just talking out loud (IE presenting) is always heard across the room. 
3. For listeners it's incredibly hard to focus on what is told by a person if there is someone else about 5 meters away telling virtually the same thing.

I understand that all of us should do an exercise like this for a grade and such, but I'm very sceptical towards the way this is going to unfold.  

Could you maybe provide some extra input on your view of this issue?

Thanks in advance,
Edser

**Comment by rm-bwana** [comment]
Hello Edser,

This is how the course has been done in every iteration and so far the teams have managed. 

Having two presentations ongoing in the same room is manageable if whoever is presenting can control their volume to suit the size of the audience (something to consider when deciding who should present). This is something the staff member present will keep note of. Of course this does not mean there will be no background noise but being able to pay attention for the 20 minutes is considered manageable. 

Also, slides on projectors are not a mandatory or necessary part of the presentation. It may seem the easiest to use but  you are free to use other presentation materials and methods. 

Teams in the past have used their own laptops, brought handouts or fill in's, shared the slides with others to follow along, created quizzes and game show-like presentations to mention just a few. We look forward to how teams will tackle the opportunity this year round as well.

If you have any questions, feel free to comment back.

Best regards,
Rob.

**Comment by rm-bwana** [comment]
Hello,

It is of course a matter of the teams rising to the challenge. When deciding who to present make sure that the person chosen will not be put off by the background noise or distraction. It is about focusing on your specific section of the audience and not trying to compete with the other group over who can speak the loudest.

If you have specific equipment request you can create an issue about it but it seems that we will be requesting the necessary equipment to ensure that each room has at least 2 projectors and/or screens to cater for the audience size. 

All the best.
