### ISSUE TITLE
Assignment 5 is gone

### ISSUE THREAD

**Issue by RonaldKruizinga** [RUG-IDS/Course-2018#27]
Hello TA's,

I was about to start the 5th assignment about text mining, but when I clicked the file it was suddenly unavailable.

Could it be made available again?

Sincerely,
Ronald Kruizinga

**Comment by rm-bwana** [comment]
Hi,

Yes that was intentionally done. We had to fix something and it will be uploaded once again soon. 

Let's leave this issue open and once it's ready I will say so here.

Rob.

**Comment by rm-bwana** [comment]
The more accurately named Assignment 04 is back online.
