### ISSUE TITLE
Missing porter tokenizer example

### ISSUE THREAD

**Issue by charx7** [RUG-IDS/Course-2018#30]
Hi, I cannot find the porter tokenizer example mentioned on the presentation, could you help me?

**Comment by willekemulder** [comment]
Hi charx7,

Do you mean the porter stemming, and the tokenizer seperately? 

In Python you can simply use:

''' Use Tokenizer '''
from nltk import word_tokenize
sentence = "try to tokenize these words as an example"
words = word_tokenize(sentence)


''' Use porter stemming '''
from nltk.stem.porter import *
stemmer = PorterStemmer()

stemmedwords = [stemmer.stem(word) for word in words]

**Comment by rm-bwana** [comment]
Hello @charx7 ,

That link will not work as it is a link to a local server which was running on George's laptop. I can check with him if he will provide it. But it is very similar to what @willekemulder suggested.

Rob

**Comment by geazzo** [comment]
Hi all,

I have now just uploaded the Porter Stemmer example on Nestor (Lecture 4 - Text Mining section).

Best regards,
George
