### ISSUE TITLE
Question about 'State of the corpus' exercise

### ISSUE THREAD

**Issue by rubenscheedler** [RUG-IDS/Course-2018#31]
Hello,
At the second step of the 'State of the corpus' exercise we are asked to plot "the best-fitting Zipf distribution". What is meant by this? A line that exactly matches Zipf's law? Or the best distribution found among the separate text files? Or something else?
Thanks in advance!

**Comment by rm-bwana** [comment]
Hello,

The first part of the question asks you to plot the word frequency vs it's position in the sorted list of occurrence. Like which shows up in examples in the lecture material. This is for the entire corpus which you have chosen to work on. 

You are free to show examples of individual texts within the corpus but is not required. This is advised only if it helps to support a point you wish to make in the report. 

The 2nd part, which I believe you are asking about, requires you to create the best fitting zipf distribution. This means a curve showing a zipf distribution on the same scale. This can be created using synthetic data. Essentially it is meant to act as a reference for what a 'pure' zipf distribution would look like to which you can compare your answers.

Hope this helps,
Rob.

**Comment by rubenscheedler** [comment]
Thanks, that's very helpful!

**Comment by edumargra** [comment]
Related with the response of Robert.
In the 'state of the corpus' exercise we are told to 'compute the term frequencies for all the documents in the corpus', as in the TFShake notebook, per each text of the corpus, or work like the whole corpus is one document, as your response seems to indicate: 'This is for the entire corpus which you have chosen to work on...You are free to show examples of individual texts within the corpus but is not required. ', even though I thought that TF is a measurement per document and TFxIDF is for corpus.
