### ISSUE TITLE
Presentation Requirement group 15 room NB 5118.0161 (28)

### ISSUE THREAD

**Issue by Carolien989** [RUG-IDS/Course-2018#34]
Dear IDS team,

The room booked for next week Monday does not have any equipments for giving a slide presentation. There is only a blackboard, not even an Computer when we checked.

Therefore, we would like a beamer with HDMI connection or another room so that we can show slides to the audience.

Can you manage that?

Best,
Carolien, group 15

p.s. Sorry for the late Issue. Firstly, a team member mailed you about this instead of making a Issue.

**Comment by rezaeisamiraa** [comment]
@Carolien989 
We will provide a beamer for you.

**Comment by rezaeisamiraa** [comment]
@Carolien989 

Please note that the extra projectors only have VGA cable and it is your responsibility to deal with it.

**Comment by Carolien989** [comment]
@rezaeisamiraa That is a pity, you are quite late informing this to us since I explicitly asked for a 
HDMI connection. I will have contact with my group how we will fix this in time.

**Comment by Daemonstool** [comment]
See #43
