### ISSUE TITLE
Zipfs fit

### ISSUE THREAD

**Issue by charx7** [RUG-IDS/Course-2018#35]
Hi mr TA, I have a question regarding the zipfs dist fit, the histogram of term freq should follow the zipfs law, but the assignment says to fit a line to the log transformation, should we plot the zipfs on top of the freq hist or log(freq hist)?

**Comment by rm-bwana** [comment]
Hello,

They should be approximately on the same scale. So if you are displaying the log of the term freq then you should show the log of the best fit line.

You can try to plot the line of best fit on the original term freq and then log both values.

Rob.

**Comment by charx7** [comment]
Makes sense! Thanks!
