### ISSUE TITLE
Question regarding dimensionality reduction

### ISSUE THREAD

**Issue by rubenscheedler** [RUG-IDS/Course-2018#36]
Hello,
We are working on the last question of the State of the corpus exercise and are a bit stuck. We performed SVD on our term matrix but we are a bit lost on how we have to visualize the results from that. The example file regarding SVD on nestor focusses on searching through that result but not visualizing or interpreting it. What exactly should we plot?

**Comment by rm-bwana** [comment]
Hello,
Yes the visualisation is not included in the material. I cannot say exactly how you should show your results as then teams may feel that their interpretation or visualisation of results may be incorrect. Visualisation is only correct when it transfers the intended information into the reader/audience. In week 2's lecture material there is a small section on visualisation towards the end of the set of slides which can help in some regards. 

Remember that dimensionality reduction is often used to represent data for visualisation (if resulting dimensions are between 1 and 3) and are best suited to showing the most distinguishable differences in the higher dimensional data. 

So with no intention of being vague or unhelpful, I would answer your question with another question:
You have been given several texts within the corpus, each similar or dissimilar to the others in various ways. If you wish to show the **most important** (dis-)similarities between the texts of a corpus, how would you do so?

Rob.

**Comment by rubenscheedler** [comment]
Thanks for your reply! We got some visualization working now.
