### ISSUE TITLE
Presentation requirements for group 14

### ISSUE THREAD

**Issue by eserco** [RUG-IDS/Course-2018#37]
Dear TAs,

Our team is going to have a powerpoint presentation, therefore, we need a projector with an HDMI port. The room will be NB 5118.0161.

Kind regards,
Team 14

**Comment by rezaeisamiraa** [comment]
@eserco 
you are informing us too late.
I cannot promise you anything but I will update you.

**Comment by rezaeisamiraa** [comment]
@eserco 
You will have a beamer :)

**Comment by rezaeisamiraa** [comment]
@eserco 
Please note that the extra projectors only have VGA cable and it is your responsibility to deal with it.
