### ISSUE TITLE
Presentation requirements for team 07

### ISSUE THREAD

**Issue by IvardeHaan2** [RUG-IDS/Course-2018#38]
We need a beamer to show our slides in room 5113.0201 at 9:30. Thank you :)

**Comment by rezaeisamiraa** [comment]
@IvardeHaan2 
you are informing us too late.
I cannot promise you anything but I will update you.

**Comment by rezaeisamiraa** [comment]
@IvardeHaan2 
You will have a beamer :)

**Comment by rezaeisamiraa** [comment]
@IvardeHaan2  
Please note that the extra projectors only have VGA cable and it is your responsibility to deal with it.
