### ISSUE TITLE
Python code

### ISSUE THREAD

**Issue by AlejoPaullier** [RUG-IDS/Course-2018#4]
Hello, i'm kind of new to Python and i'm having problems running the code provided on excercise 4. So far I have managed to see the light blue graph. However I do not know which command I have to write to perform operations. Could anybody enlighten me?

**Comment by DaniMarcos95** [comment]
Hi,
you could make use of the numpy library which is already imported at the beginning of the code as np. To perform an operation, let's say the log, you could for example write `samples = np.log(samples)`. Just take a look at numpy and its documentation.

**Comment by loranoosterhaven** [comment]
Has there been any sample code provided? I cannot find it.

**Comment by DaniMarcos95** [comment]
The code you should use is in the question 4 statement right before point 1.

**Comment by rm-bwana** [comment]
Hello,
As @DaniMarcos95 says, numpy is often the best package to perform advanced numerical or mathematical operations in python.

You can find the documentation regarding some of the functions you need here: [https://docs.scipy.org/doc/numpy/reference/routines.math.html](url)

You would then need to find the appropriate place in the code to put the functions and run the code once again for each operation you want to try.

@loranoosterhaven are you sure you cannot see the code? If not, start a new issue and we will try to solve it there.

Rob.

**Comment by AlejoPaullier** [comment]
Thank you very much for the recomendation @DaniMarcos95  @rm-bwana .
