### ISSUE TITLE
Question about 'Your own search engine'

### ISSUE THREAD

**Issue by PJvanVliet** [RUG-IDS/Course-2018#41]
Hello,

A question about the search engine exercise: there is an ambiguity in:
'... returns the text in the corpus that most likely talks about the description in the string.'

What does that mean?
1. "... returns the title of the text ..."
2. "... returns the full text ..." (and if so, in case there is no clear top hit, does it need to output the full text of all 10 texts?)
3. "...  returns a snippet of the text ..." (say, the part of the specific text that contains those words, as you get when searching with Google).

Kind regards,

Pieter van Vliet

**Comment by rm-bwana** [comment]
Hello,

For this exercise returning the name of the text is sufficient. Any extra functionality would be up to you.

Best,
Rob.
