### ISSUE TITLE
Representing results with jupyter notebook

### ISSUE THREAD

**Issue by Mantsje** [RUG-IDS/Course-2018#42]
Hi,

We put all our code in a jupyter notebook. This also contains all of our results. Now we assume that we have to write a report again this week which has a results section. Putting in all results would give quite a lot of pages and is kind of a hassle as everything is nice and organized in the notebook.

Now our question: Is it okay to leave (most of) the results in the notebook and possibly refer to them from the report? (For example only include the most significant results in the report)
Or should everything be ported to the report?

Thanks in advance,
Edser

**Comment by rm-bwana** [comment]
Hello Edser,

This question was possibly answered in the lab, but just for those who wish to have a point of reference here I will answer.

You do not have to put in all your code and results in your report. This report is intended to teach your fellow students about the topic you covered. If the code and results do not necessarily help this process then they can be attached and referenced where necessary but do not need to form part of your main report. 

So no; do not copy over everything. Keep the report concise and include only that which is necessary.

Best,
Rob.
