### ISSUE TITLE
Does Teams 2, 4, 14 & 16 hava a VGA-HDMI converter? or a Laptop with VGA port?

### ISSUE THREAD

**Issue by Carolien989** [RUG-IDS/Course-2018#43]
Dear Teams 2, 4, 14 & 16,

The TA's were not able to have beamer with a proper HDMI cable or port. We have an presentation to show and maybe some jupyter notebook demo on a beamer. However, we do not have a laptop with a VGA port nor a converter for that in such a short notice.

Does anyone has this available and can help us by borrowing it to us for the first presentation? 

Hope we can all help each other out! 

Best,
Group 15

**Comment by Daemonstool** [comment]
Hi, 

I will bring a hdmi cable. I heard from another TA that the beamers should be hdmi compatible (that's what the reception said to her). It could not hurt to bring a VGA adapter in case the reception was wrong. 

See you tomorrrow!

Kind regards,
Henry

**Comment by Carolien989** [comment]
Oh that would be wonderful. Thank you!
