### ISSUE TITLE
Non trivial quesions

### ISSUE THREAD

**Issue by RUKip** [RUG-IDS/Course-2018#44]
Hi,

So in the assignment it says we have to write down and answer a non-trivial question. What is considered non trivial? And what is the goal of the question?(make reader think, test if the reader read report, etc ..) 

Should we write down a question which is open and cannot be wrong, e.g. what would be your choice for this kind of data-set? If so how can we give an "correct" answer.
Or should we ask a question regarding what we wrote in the report, e.g. what is the difference between bagging & boosting?

Kind regards,
Team 18

**Comment by rm-bwana** [comment]
Hello,

The goal of the non-trivial questions is to demonstrate to the readers (and us) that you have read up on the topic more than just the summary you would have created for the presentation and the report as well as show them what sort of things are part of the more advanced concepts of the topic you covered.

These are meant to have an answer (so not too open-ended) but should not be obvious answers that anyone could answer (hence non-trivial).

An example: consider the presentation of Text Analysis last week. A non-trivial question would be: _How is it then possible to use the text analysis methods developed on English for languages such as German/Dutch which have compound nouns with different meanings?_

The answer to this may not be too straight forward and shows that you have done more than read the basics.

I would give a relevant example but it will likely be used by someone or they might claim to have intended to ask something similar. 

Hope this helps,
Rob
