### ISSUE TITLE
How to interpret the Columns of the datasets for clustering

### ISSUE THREAD

**Issue by RonaldKruizinga** [RUG-IDS/Course-2018#45]
Hello, 
we were wondering what the columns of the dataset represented, as they are helpfully named V1-V6 and V1-V3.

Are the columns in the same order as they are mentioned in the assignment description (x,y,z, Vx, Vy, Vz) for the 6d and (Energy, angularmomentum, zmomentum) for the 3d csv?

Sincerely,

**Comment by rm-bwana** [comment]
Hi,

Yes you can assume they appear in the order in the data files as listed in the assignment.

Rob.
