### ISSUE TITLE
Hopkins

### ISSUE THREAD

**Issue by RUKip** [RUG-IDS/Course-2018#50]
Hi for excericse 2 we get the tip to use hopkins to detect the difference between 3d an 6d samples from the datasets. However the values from our hopkins are similiair for both 3d and 6d. What should we pay attention though? Is it correct to assume there is no difference on this point? Or on what other basis can we differentiate?

**Comment by rm-bwana** [comment]
Hi,

Do not rely only on this one measure. You can of course mention your output and explain what it means but do not limit yourselves to this being the only thing you consider to differentiate the 2 datasets.

Rob.
