### ISSUE TITLE
1.1B PCA and tSNE?

### ISSUE THREAD

**Issue by SKMuller** [RUG-IDS/Course-2018#51]
For exercise 1.1B we are asked to embed the data using PCA and tSNE. How are we supposed to interpret this question formulation?
Are we supposed to first reduce the dimensionality of the data with PCA and then apply tSNE on the principal components of our data and plot the results? Or are we supposed to plot the first principal components of our data and compare that to a plot of the tSNE reduction of our data?

**Comment by rm-bwana** [comment]
Hi,

Both PCA and tSNE are dimensionality reduction techniques so they should both be applied to the data independently. Both can produce visualisations in 2 dimensions for this reason. The differences between them in terms of how they go about it can be easily found online as they are both very popular algorithms to use.

You have to do both of them independently and then compare the results they provide. 

Rob.
