### ISSUE TITLE
Calendar Entry: Presentations

### ISSUE THREAD

**Issue by NF997** [RUG-IDS/Course-2018#52]
There is a calendar entry for 23.10.18 13:00 stating "[Introduction to Data Science] - presentations".
What does that mean?

**Comment by rm-bwana** [comment]
Hi,

This is a session we like to have at the end of the course to go over things that people found challenging and difficult as well as to highlight good approaches that certain teams carried out.

If your team has received a good grade in one or more of the assignments you may be asked to show your classmates what you did in a short 10-15 min presentation (You will not be graded for this)

We will let you know about the specifics towards the end of the week or during Monday's lecture.

Rob.
