### ISSUE TITLE
Assignment 7 1.1a % of variance analysis

### ISSUE THREAD

**Issue by Mantsje** [RUG-IDS/Course-2018#55]
Hi,

We were wondering how to answer this part of the question:
```
How many features explained a certain percentage of the variance in the dataset?
```
This is rather hard with just the eigen values/vectors and ANOVA.
We have a way to get the features that are known to be important, but we have no idea how to map these to the percentage of variance they explain. Can you help us?

**Comment by rm-bwana** [comment]
Hi,

Eigenvectors/values and ANOVA are exactly for the reason of determining or investigating which features influence the underlying structure the most/more than others. I would say take some time to read up on each procedure and what the results mean and how to interpret them. The answers you get from running the algorithms should be most of what you need to answer the question.

Rob.
