### ISSUE TITLE
Confusing question

### ISSUE THREAD

**Issue by RUKip** [RUG-IDS/Course-2018#56]
Hi,

This is the text of (b) ensemble:

"Using your most promising experimental settings from the
above to build an ensemble classifer and perform classification. Explain which models
(combination of which classifier and which experimental settings) you selected. Com-
pare to random forests, an ensemble build with decision trees on random subsets of the
features. (Of course you can still limit the number of features before-hand removing the
least promising ones to increase performance)" 

We are confused on how to interpret the question, we have to compare our decision tree and knn models from the previous assignment with the "decision trees on random subsets of the
features" AKA random forests? Or do we need to compare random forests with other decision trees which are "ensemble build with decision trees on random subsets of the
features"? 

Kind regards,
Team 18

**Comment by rm-bwana** [comment]
Hi,

In (a) of the question you hopefully would have found some settings of knn or DT which perform better than others. 

Building on this, in (b) you would combine the best performing of these into a self-built ensemble classifier (do you understand how to do this?).

You then compare your self-built ensemble with the random-forest algorithm, which can be found pre-implemented in certain packages and libraries so you should not have to implement it yourself. 

In your report we would then expect you to:
- Explain why you chose the base models which you used to form your self-built ensemble
- Report on how it performs compared to a standard ensemble technique (random forest) which is regularly used. 

Higher marks can be achieved by not only reporting the results but also why you think your self-built ensemble under-/over-performs the random forest.

Hope that is clear,
Rob.
