### ISSUE TITLE
Boxplots for 1.1a

### ISSUE THREAD

**Issue by RUKip** [RUG-IDS/Course-2018#59]
Hi,

We are asked to make a boxplot of our features to visualize the top features and some less significant ones. However we can't seem to figure out why a boxplot and what the axis should be. We want to show visualize significant features so the density/median should be around what? The amount of features needed to get a good result? Then we get a bar plot not a box plot. The location of the most important features in index? That's also a useless statistic. 

Any tips on what the boxplot should show?

Kind regards,
Team 18

**Comment by rm-bwana** [comment]
Hi,

Pick some of the best performing features and some of the less performing features. For each feature plot the values within them in boxplots. Considering they are important features in determining classification outcome, you may find plotting boxplots for the healthy and non-healthy patients side by side per feature will show something of note. 

Rob.
