### ISSUE TITLE
Question regarding Q2 of Test 1.

### ISSUE THREAD

**Issue by ifeelgitty** [RUG-IDS/Course-2018#6]
Part of Q2 reads "2. Perform 3 different types of discretization on the nationality feature. Provide the results." 
Am I assuming correctly that in question 2, the nationality feature is supposed to be binaryzed instead of discretizized?

Cheers!

**Comment by rm-bwana** [comment]
Hello,
Discretisation is not limited to continuous values only. It can be applied to categorical data as well. Slide 41 (+/-) of the lecture material of week 1 show 3 different examples of how categorical values could be discretised.
