### ISSUE TITLE
The effect of bonus assignment

### ISSUE THREAD

**Issue by atianhlu** [RUG-IDS/Course-2018#60]
Dear TA,

We're still a bit confused about how the bonus assignment works... Does it mean that it will only add to the insufficient part of 7 assignments, for example, if I obtain 350 already, the bonus assignment would not add any more to that, but if I have 300 from 7 assignments, the bonus assignment can give me at most 50? And does it help with the final overall grade?  

I'm sorry for bothering you with this question since you already explained but I didn't get it clear yet and my friends are confused about it too, so it would be better we can have text explanation here. Thank you in advance for your work!

**Comment by rm-bwana** [comment]
Hello,

Hopefully I can clarify it for you. The bonus assignment will add on to whatever amount of points you already have. If you have 350 points after all 7 original assignments are graded, whatever you get in the bonus assignment will add to that amount. So you could get a maximum of 430 points. 

In essence all the bonus assignments which have been part of the regular assignments as well as this bonus assignment will add to the amount of points you get as part of the normal assignment work. 

The final amount you have collected will still be graded out of 700 so any attempt at taking the bonus assignment is guaranteed to improve your final assignment grade (unless you get a 0; I'm not saying you will but just to clarify).

Is this clear or should I provide a better example as well?

Rob.
