### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by RaduCimpean** [RUG-IDS/Course-2018#61]
Where can we find the form for the peer review?

**Comment by rm-bwana** [comment]
Hi,

You were 30 minutes early. The announcement has gone out now.

The link should be in your team repository master branch.

Rob.

**Comment by RaduCimpean** [comment]
That was interesting :). And then I have another question. When I try to copy and paste the form code I get the following message: "You need permission This form can only be viewed by users in the owner's organization." I am using the same laptop as a I used during the whole course, so there shouldn`t have been any problems. How can I access the form?

**Comment by rm-bwana** [comment]
Hi,

If you are using Chrome, make sure it is signed into your @student.rug.nl account and not your private one.  The form is only accessible by email addresses which belong to rug.nl but Chrome has problems applying the right account to a page sometimes. 

If all else fails, sign out of all accounts in Chrome and only sign in with your student.rug.nl account and then try to access the link.

Rob.
