### ISSUE TITLE
Exam on paper question

### ISSUE THREAD

**Issue by RonaldKruizinga** [RUG-IDS/Course-2018#62]
Hello,

since there is a chance that you have to make the exam on paper, are we allowed to bring a calculator (and which kind), as calculating log, for example for splitting, is not my favorite thing to do without a calculator :)

**Comment by rm-bwana** [comment]
Hello,

Calculators should be allowed regardless whether you are doing the digital or paper exam. 

I do not speak for the university, but from my experience it should be a simple scientific calculator without any special graphing capabilities.

All the best,
Rob
