### ISSUE TITLE
Answers to Bonus Assignment

### ISSUE THREAD

**Issue by yulanvanoppen** [RUG-IDS/Course-2018#64]
Dear TAs,

I am wondering what the actual answers were for the bonus assignment. I did not get full points, even though I expected as much, and I think this is the case for other students as well. 

Kind regards,

**Comment by rm-bwana** [comment]
Hi,

As per the announcement, released yesterday I believe, there is a time on Friday for you to go through your answers with dr. Bunte in her office. 

If you wish to ask questions via email you may do so beforehand as well, as several students already have. We can then take a look at your submitted test and suggest where you made a mistake in your approach. 

Rob.

**Comment by yulanvanoppen** [comment]
Dear Rob,

Thank you for your reply! Sorry, I had completely missed that.


Kind regards,

Yulan van Oppen
