### ISSUE TITLE
Team assignement 

### ISSUE THREAD

**Issue by charx7** [RUG-IDS/Course-2018#8]
Hi Im Carlos Huerta student Number s3743071 I was checking and I wasnt assigned a team for the course, I have already submitted the Google form, could you helo me out?

**Comment by willekemulder** [comment]
Hello! I just heard that Thijs Eker, who is in my group (21) quitted the course. Maybe we could contact the TA's and ask if you can join our group?

**Comment by rm-bwana** [comment]
Hello Carlos,

Which form did you fill in and when?

Rob.

**Comment by charx7** [comment]
Hi,
I filled the google form of team expectations, I filled it on saturday since I just got here from overseas.

Thanks.
